package com.example.restservice.service;

import com.example.restservice.dto.FlatLinkedWordDto;
import com.example.restservice.model.Word;
import com.example.restservice.model.Page;
import com.example.restservice.repository.AuthorRepository;
import com.example.restservice.repository.PageRepository;
import com.example.restservice.repository.WordRepository;
import jakarta.annotation.Nullable;
import org.jspecify.annotations.NullMarked;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;
import java.util.Objects;

@Service
@NullMarked
public class WordService {

    private final WordRepository wordRepository;
    private final PageRepository pageRepository;
    private final AuthorRepository authorRepository;

    // Update constructor injection
    public WordService(WordRepository wordRepository, PageRepository pageRepository, AuthorRepository authorRepository) {
        this.wordRepository = wordRepository;
        this.pageRepository = pageRepository;
        this.authorRepository = authorRepository;
    }

    @Transactional(readOnly = true)
    public List<Word> getAllWords() {
        return wordRepository.findAll();
    }

    /*
    This should always be used instead of getWordById.
    When a word object needs to be retrieved, we need to show a flat word object with the nextWordId property.
    */
    @Transactional(readOnly = true)
    public FlatLinkedWordDto getFlatWordById(Long id) {
        Word word = wordRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Word not found"));
        
        // Find next ID safely
        Long nextWordId = (word.getNextWord() != null) ? word.getNextWord().getId() : null;
        
        // Look up previous ID efficiently using the repository query
        Long previousWordId = wordRepository.findByNextWord(word)
                .map(Word::getId)
                .orElse(null); // Returns null if this word is the head of the list
        
        return new FlatLinkedWordDto(word.getId(), word.getContent(), nextWordId, previousWordId);
    }

    /*
    This should not be called from the front end as it will recursively return all words in the database.
    */
    @Transactional(readOnly = true)
    public Word getWordById(Long id) {
        return wordRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Word not found"));
    }

    /**
     * Create a word.
     *
     * Inserts a word after the previous word.
     * If there is no previous word (both previousWordId and previousLocalId are missing/null), assume we are at the 
     * beginning and change the current page's first word to the word we are creating.
     * 
     * If just the previousLocalId is available, that means we connect the word to another word that is in-flight
     * rather than looking at the database. Hopefully this is handled gracefully by Spring Boot's magic.
     *
     * @param newWord A word to be added to the server.
     * @param currentPageId Used to decide if we should change the firstWord or lastWord of the current page.
     * @param localId The unique identifier generated by the client for this new word.
     * @param previousWordId Optional database identifier of the anchor word.
     * @param previousLocalId Optional client identifier of the anchor word (takes precedence).
     * @return the created word.
     */
    @Transactional
    public Word createWord(Word newWord, Long currentPageId, String localId,
                           @Nullable Long previousWordId, @Nullable String previousLocalId,
                           String username) {
        newWord.setLocalId(localId);

        // FETCH THE AUTHENTICATED AUTHOR AND LINK THEM TO THE WORD
        var author = authorRepository.findAuthorByUsername(username)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Author profile not found for creation context: " + username));
        newWord.setAuthor(author);

        // 1. Determine the previous word anchor based on identity precedence
        Word previousWord = null;
        if (previousLocalId != null && !previousLocalId.isBlank()) {
            previousWord = wordRepository.findByLocalId(previousLocalId)
                    .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Previous word not found via localId: " + previousLocalId));
        } else if (previousWordId != null) {
            previousWord = wordRepository.findById(previousWordId)
                    .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Previous word not found via DB ID: " + previousWordId));
        }

        // 2. Splice into mid-chain or end-chain if an anchor was found
        if (previousWord != null) {
            // Cache the next word link so we don't lose it
            Word nextWordAnchor = previousWord.getNextWord();

            // Sever the link on the previous word immediately to free up the unique constraint
            previousWord.setNextWord(null);
            wordRepository.saveAndFlush(previousWord); // Force the DB to see next_word_id is now NULL

            // Give the cached link to the new word
            newWord.setNextWord(nextWordAnchor);
            Word savedWord = wordRepository.saveAndFlush(newWord); // Save newWord safely

            // Point the previous word to the newly saved word
            previousWord.setNextWord(savedWord);
            wordRepository.save(previousWord);

            // Update firstWord or lastWord boundaries of current page
            Page currentPage = pageRepository.findById(currentPageId)
                    .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Current page not found"));

            Page pageWithLastWord = pageRepository.findByLastWord(previousWord).orElse(null);
            Page pageWithFirstWord = pageRepository.findByFirstWord(savedWord.getNextWord()).orElse(null);

            if (pageWithLastWord != null && Objects.equals(pageWithLastWord.getId(), currentPageId)) {
                currentPage.setLastWord(savedWord);
            }

            if (pageWithFirstWord != null && Objects.equals(pageWithFirstWord.getId(), currentPageId)) {
                currentPage.setFirstWord(savedWord);
            }

            pageRepository.save(currentPage);

            return savedWord;
        }

        // 3. Fallback: If both qualifiers are null, prepend/prepend-isolated to the specified page
        Page targetPage = pageRepository.findById(currentPageId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Target page not found"));
        
        newWord.setNextWord(targetPage.getFirstWord());
        Word savedWord = wordRepository.saveAndFlush(newWord);
        
        targetPage.setFirstWord(savedWord);
        pageRepository.save(targetPage);
        
        return savedWord;
    }

    @Transactional
    public Word updateWord(Long id, Word wordDetails) {
        return wordRepository.findById(id)
                .map(existingWord -> {
                    existingWord.setContent(wordDetails.getContent());
                    
                    // Map the nextWord relationship safely
                    if (wordDetails.getNextWord() != null) {
                        existingWord.setNextWord(wordDetails.getNextWord());
                    }
                    
                    return wordRepository.save(existingWord);
                })
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Word not found"));
    }

    @Transactional
    public void deleteWord(Long id) {
        Word wordToDelete = wordRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Word not found"));

        Word nextWord = wordToDelete.getNextWord();
        Word previousWord = wordRepository.findByNextWord(wordToDelete).orElse(null);

        patchPageBoundaries(wordToDelete, previousWord, nextWord);

        if (previousWord != null) {
            previousWord.setNextWord(nextWord);
            wordRepository.save(previousWord);
        }

        wordToDelete.setNextWord(null);
        wordRepository.saveAndFlush(wordToDelete);
        wordRepository.delete(wordToDelete);
    }

    private void patchPageBoundaries(Word wordToDelete, @Nullable Word previousWord, @Nullable Word nextWord) {
        // Fix page where this was the first word
        pageRepository.findByFirstWord(wordToDelete).ifPresent(page -> {
            if (wordToDelete.equals(page.getLastWord())) {
                page.setFirstWord(null);
                page.setLastWord(null);
            } else {
                page.setFirstWord(nextWord);
            }
            pageRepository.save(page);
        });

        // Fix page where this was the last word
        pageRepository.findByLastWord(wordToDelete).ifPresent(page -> {
            page.setLastWord(previousWord);
            pageRepository.save(page);
        });
    }
}
