spring.application.name=demo

# Enabling H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Turn statistics on
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=debug

# Show all queries
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Defer datasource initialization
spring.jpa.defer-datasource-initialization=true

