# PostgreSQL Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000

# 1. Change this to 'never' so it doesn't look for import.sql/schema.sql on every boot
spring.sql.init.mode=never

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create

# Turn statistics on
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=debug

# Defer datasource initialization (Can be left false or removed if init.mode=never)
spring.jpa.defer-datasource-initialization=false

# Default fallback for local development
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Define rate limits
ratelimit.global.capacity=50000
ratelimit.ip.capacity=1000
ratelimit.user.capacity=500
ratelimit.websocket.capacity=100