package com.bookolab.restservice.service;

import java.util.List;
import java.util.Objects;

import org.jspecify.annotations.NullMarked;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import com.bookolab.restservice.dto.DeletionResult;
import com.bookolab.restservice.dto.FlatLinkedWordDto;
import com.bookolab.restservice.dto.WordNodeDto;
import com.bookolab.restservice.enums.ReactionType;
import com.bookolab.restservice.model.Author;
import com.bookolab.restservice.model.Page;
import com.bookolab.restservice.model.Word;
import com.bookolab.restservice.repository.AuthorRepository;
import com.bookolab.restservice.repository.PageRepository;
import com.bookolab.restservice.repository.ReactionRepository;
import com.bookolab.restservice.repository.WordRepository;

import jakarta.annotation.Nullable;

@Service
@NullMarked
public class WordService {

    private final WordRepository wordRepository;
    private final PageRepository pageRepository;
    private final AuthorRepository authorRepository;
    private final ReactionRepository reactionRepository;
    private final ReactionStatsService reactionStatsService;

    // Update constructor injection
    public WordService(WordRepository wordRepository, PageRepository pageRepository, AuthorRepository authorRepository, ReactionRepository reactionRepository, ReactionStatsService reactionStatsService) {
        this.wordRepository = wordRepository;
        this.pageRepository = pageRepository;
        this.authorRepository = authorRepository;
        this.reactionRepository = reactionRepository;
        this.reactionStatsService = reactionStatsService;
    }

    @Transactional(readOnly = true)
    public List<Word> getAllWords() {
        return wordRepository.findAll();
    }

    /*
    This should always be used instead of getWordById.
    When a word object needs to be retrieved, we need to show a flat word object with the nextWordId property.
    */
    @Transactional(readOnly = true)
    public FlatLinkedWordDto getFlatWordById(Long id) {
        Word word = wordRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Word not found"));

        String authorName = word.getAuthor() != null ? word.getAuthor().getUsername() : "Anonymous";
        // Find next ID safely
        Long nextWordId = (word.getNextWord() != null) ? word.getNextWord().getId() : null;
        
        // Look up previous ID efficiently using the repository query
        Long previousWordId = wordRepository.findByNextWord(word)
                .map(Word::getId)
                .orElse(null); // Returns null if this word is the head of the list
        
        FlatLinkedWordDto flatLinkedWordDto = new FlatLinkedWordDto(word.getId(), word.getContent(), nextWordId, previousWordId, authorName);

        return flatLinkedWordDto;
    }

    /*
    This should not be called from the front end as it will recursively return all words in the database.
    */
    @Transactional(readOnly = true)
    public Word getWordById(Long id) {
        return wordRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Word not found"));
    }

    /**
     * Create a word.
     *
     * Inserts a word after the previous word.
     * If there is no previous word (both previousWordId and previousLocalId are missing/null), assume we are at the 
     * beginning and change the current page's first word to the word we are creating.
     * 
     * If just the previousLocalId is available, that means we connect the word to another word that is in-flight
     * rather than looking at the database. Hopefully this is handled gracefully by Spring Boot's magic.
     *
     * @param newWord A word to be added to the server.
     * @param currentPageId Used to decide if we should change the firstWord or lastWord of the current page.
     * @param localId The unique identifier generated by the client for this new word.
     * @param previousWordId Optional database identifier of the anchor word.
     * @param previousLocalId Optional client identifier of the anchor word (takes precedence).
     * @return the created word.
     */
    @Transactional
    public Word createWord(Word newWord, Long currentPageId, String localId,
                           @Nullable Long previousWordId, @Nullable String previousLocalId,
                           String username) {
        newWord.setLocalId(localId);

        // FETCH THE AUTHENTICATED AUTHOR AND LINK THEM TO THE WORD
        var author = authorRepository.findAuthorByUsername(username)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Author profile not found for creation context: " + username));
        newWord.setAuthor(author);

        // 1. Determine the previous word anchor based on identity precedence
        Word previousWord = null;
        if (previousLocalId != null && !previousLocalId.isBlank()) {
            previousWord = wordRepository.findByLocalId(previousLocalId).orElse(null);
            // There might not be a previous word in memory in the event that the user was rate limited.
            // In this case they may have kept typing until they received another token.
            // When this happens, if they type another word, findByLocalId will not find a previous word by local id.
            if (previousWord == null) {
                // In this case we just return a dummy word that isn't connected to anything and
                // does not get saved to the database.
                return new Word("...", "dummy_word");
            }
                    // .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Previous word not found via localId: " + previousLocalId));
        } else if (previousWordId != null) {
            previousWord = wordRepository.findById(previousWordId)
                    .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Previous word not found via DB ID: " + previousWordId));
        }

        // 2. Splice into mid-chain or end-chain if an anchor was found
        if (previousWord != null) {
            // Cache the next word link so we don't lose it
            Word nextWordAnchor = previousWord.getNextWord();
            // Sever the link on the previous word immediately to free up the unique constraint
            previousWord.setNextWord(null);
            wordRepository.saveAndFlush(previousWord); // Force the DB to see next_word_id is now NULL

            // Give the cached link to the new word
            newWord.setNextWord(nextWordAnchor);
            Word savedWord = wordRepository.saveAndFlush(newWord); // Save newWord safely

            // Point the previous word to the newly saved word
            previousWord.setNextWord(savedWord);
            wordRepository.save(previousWord);

            // Update firstWord or lastWord boundaries of current page
            Page currentPage = pageRepository.findById(currentPageId)
                    .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Current page not found"));

            // Case 1: The current page is completely empty (this is its first and only word)
            if (currentPage.getFirstWord() == null) {
                currentPage.setFirstWord(savedWord);
                currentPage.setLastWord(savedWord);
            }
            // Case 2: We are inserting a word right at the beginning of this page
            // (i.e., the previous word belonged to the prior page, and this page's old first word is now our next word)
            else if (Objects.equals(currentPage.getFirstWord(), savedWord.getNextWord())) {
                currentPage.setFirstWord(savedWord);
            }
            // Case 3: We are appending to the very end of this page
            else if (Objects.equals(currentPage.getLastWord(), previousWord)) {
                currentPage.setLastWord(savedWord);
            }

            pageRepository.save(currentPage);

            return savedWord;
        }

        // 3. Fallback: If both qualifiers are null, prepend to the specified page
        Page targetPage = pageRepository.findById(currentPageId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Target page not found"));

        if (targetPage.getFirstWord() != null) {
            // Page already has content; prepend to the current page's chain
            newWord.setNextWord(targetPage.getFirstWord());
        } else {
            // Page is empty! Look ahead to find the next non-empty page's first word
            Word nextChainHead = null;
            Long nextId = currentPageId + 1;

            // Scan ahead up to a reasonable limit or until no more pages exist
            while (true) {
                java.util.Optional<Page> nextPageOpt = pageRepository.findById(nextId);
                if (nextPageOpt.isEmpty()) {
                    break; // No more pages in DB
                }
                Page nextPage = nextPageOpt.get();
                if (nextPage.getFirstWord() != null) {
                    nextChainHead = nextPage.getFirstWord();
                    break; // Found the next link in the chain
                }
                nextId++;
            }
            newWord.setNextWord(nextChainHead);
        }

        Word savedWord = wordRepository.saveAndFlush(newWord);

        // If the page was empty, this new word is also the last word
        if (targetPage.getFirstWord() == null) {
            targetPage.setLastWord(savedWord);
        }

        targetPage.setFirstWord(savedWord);
        pageRepository.save(targetPage);

        return savedWord;
    }

    @Transactional
    public Word updateWord(Long id, Word wordDetails) {
        return wordRepository.findById(id)
                .map(existingWord -> {
                    existingWord.setContent(wordDetails.getContent());
                    
                    // Map the nextWord relationship safely
                    if (wordDetails.getNextWord() != null) {
                        existingWord.setNextWord(wordDetails.getNextWord());
                    }
                    
                    return wordRepository.save(existingWord);
                })
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Word not found"));
    }

    @Transactional
    public DeletionResult deleteWord(Long id, Long currentPageId, String authorName) {
        Word wordToDelete = wordRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Word not found"));

        Author author = authorRepository.findAuthorByUsername(authorName)
                .orElseThrow(() -> new UsernameNotFoundException("Author not found"));

        Long likes = reactionRepository.countByWordIdAndReactionType(id, ReactionType.LIKE);
        Long dislikes = reactionRepository.countByWordIdAndReactionType(id, ReactionType.DISLIKE);

        long creditsRequired = likes - dislikes;

        byte multiplier = 1;

        if (wordToDelete.getAuthor() != null && wordToDelete.getAuthor().getId().equals(author.getId())) {
            multiplier = 2;
        }

        if (!hasEnoughDeleteCredits(author, creditsRequired * multiplier)) {
            System.out.println("\uD83D\uDEAB User does not have enough delete credits.");
            DeletionResult result = new DeletionResult(null, null);
            result.setValid(false);
            return result;
        }

        Word nextWord = wordToDelete.getNextWord();
        Word previousWord = wordRepository.findByNextWord(wordToDelete).orElse(null);

        // Safely extract IDs, defaulting to null if the object is null
        Long previousId = (previousWord != null) ? previousWord.getId() : null;

        // Unless we are the last word of the current page, set the next word DTO
        WordNodeDto nextWordNodeDto = null;
        Page nextPage = pageRepository.findById(currentPageId + 1).orElse(null);
        int i = 2;
        while (nextPage != null && nextPage.getFirstWord() == null) {
            nextPage = pageRepository.findById(currentPageId + i).orElse(null);
            i++;
        }
        // Only check the first word if nextPage actually exists
        if (nextPage != null && nextPage.getFirstWord() != null
                && !nextPage.getFirstWord().equals(nextWord)) {
            nextWordNodeDto = new WordNodeDto(
                    nextWord.getId(),
                    nextWord.getContent(),
                    authorName);
        }

        DeletionResult result = new DeletionResult(previousId, nextWordNodeDto);

        // Broadcast stats for the author whose word is being deleted
        reactionStatsService.broadcastSubtractionOfLikesAndDislikesForWord(wordToDelete.getId());

        patchPageBoundaries(wordToDelete, previousWord, nextWord);

        if (previousWord != null) {
            previousWord.setNextWord(nextWord);
            wordRepository.save(previousWord);
        }

        wordToDelete.setNextWord(null);
        wordRepository.saveAndFlush(wordToDelete);
        wordRepository.delete(wordToDelete);

        author.incrementCreditsSpent(creditsRequired);
        authorRepository.save(author);
        reactionStatsService.broadcastNewCreditsSpent(author);
        return result;
    }

    private void patchPageBoundaries(Word wordToDelete, @Nullable Word previousWord, @Nullable Word nextWord) {
        // Fix page where this was the first word
        pageRepository.findByFirstWord(wordToDelete).ifPresent(page -> {
            if (wordToDelete.equals(page.getLastWord())) {
                page.setFirstWord(null);
                page.setLastWord(null);
            } else {
                page.setFirstWord(nextWord);
            }
            pageRepository.save(page);
        });

        // Fix page where this was the last word
        pageRepository.findByLastWord(wordToDelete).ifPresent(page -> {
            page.setLastWord(previousWord);
            pageRepository.save(page);
        });
    }

    public boolean hasEnoughDeleteCredits(Author author, Long creditsRequired) {
        // System.out.println(author.getUsername() + " spent " + author.getCreditsSpent() + " credits.");
        return reactionRepository.countLikesMinusDislikes(author.getId()) - author.getCreditsSpent() >= creditsRequired;
    }
}
